---
- hosts: all

  tasks:

    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: latest
        update_cache: true
      become: true

    - name: Build container image locally
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: build
        state: present
        build:
          path: ..
          platform: linux/amd64
        force_source: true
      delegate_to: 127.0.0.1

    - name: Export container image locally
      community.docker.docker_image:
        name: "{{ image_name }}"
        archive_path: /tmp/"{{ image_name }}"-img.tar
        source: local
      delegate_to: 127.0.0.1

    - name: upload_image_to_server
      ansible.builtin.copy:
        src: /tmp/"{{ image_name }}"-img.tar
        dest: /tmp/"{{ image_name }}"-img.tar

    - name: Import container image on server
      community.docker.docker_image:
        name: "{{ image_name }}"
        load_path: /tmp/"{{ image_name }}"-img.tar
        source: load
        force_source: true
        state: present
      become: true

    - name: Ensure .env file exists
      ansible.builtin.template:
        src: env.j2
        dest: ~/{{ env_name }}
        force: false
      vars:
        secret_key: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

    - name: Ensure db.sqlite3 file exists outside container
      ansible.builtin.file:
        path: /home/mattquinn/{{ db_name }}
        state: touch

    - name: Run container
      community.docker.docker_container:
        name: "{{ image_name }}"
        image: "{{ image_name }}"
        state: started
        recreate: true
        env_file: ~/{{ env_name }}
        mounts:
          - type: bind
            source: /home/mattquinn/{{ db_name }}
            target: /src/{{ db_name }}
        ports: "{{ port }}:8888"

    - name: Run migration inside container
      community.docker.docker_container_exec:
        container: "{{ image_name }}"
        command: poetry run python ./manage.py migrate
